import Navigation from "../Navigation/Navigation"
import Head from "next/head"
import styled from 'styled-components';
import { ThemeProvider } from 'styled-components';
import GlobalStyle from 'styles/global'
import { theme } from 'styles/theme'

const ContainerBody = styled.body`
  background-color: red;
`;

const Container = (props: any) => (
    <ContainerBody>
        <ThemeProvider theme={theme}>
            <GlobalStyle />
            <Head>
                <title>Punkies y Cerebro</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet" />
            </Head>
            <Navigation />
            {props.children}
        </ThemeProvider>
    </ContainerBody>
)

export default Container
