import Navigation from "../Navigation/Navigation"
import Head from "next/head"
import styled from 'styled-components';
import { ThemeProvider } from 'styled-components';
import GlobalStyle from 'styles/global'
import { theme } from 'styles/theme'

// theme is also fully typed
const Title = styled.h1`
  color: red;
`;

const Container = (props: any) => (
    <div>
        <ThemeProvider theme={theme}>
            <GlobalStyle />
            <Head>
                <title>Punkies y Cerebro</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <div>
                {props.children}
            </div>
        </ThemeProvider>
    </div>
)

export default Container
