import Head from 'next/head'
import Container from 'components/Container/Container';
import styled from 'styled-components';


export default function Home() {

  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <p>hello</p>
      </Container>
    </div >
  )
}


