import Head from 'next/head'
import Slider from 'components/Showcase/Slider/Slider'
import Noticias from 'components/Noticias/Noticias'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      <Noticias />
    </div>
  )
}


