import Head from 'next/head'
import Image from 'next/image'
import Container from '../components/Container/Container'
import styled from 'styled-components';
import { useState } from 'react';
import { ThemeProvider } from 'styled-components';


export default function Home() {

  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

          <h1>from indexddddfsdf</h1>
       
 
      </Container>
    </div >
  )
}


